### ISSUE TITLE
elementResize not working on mac

### ISSUE THREAD

**Issue by amit1911** [digidem/react-dimensions#25]
I am trying to resize the right panel once the left panel is hidden by using `{elementResize: true}`. This works fine on PC but not on MAC. The left and right panels are flex items. When the left panel is hidden, i noticed that the dimensions 'div' wrapper is expanding properly but it is not passing the new width to the child. Any ideas?

**Comment by gmaclennan** [comment]
Can you post some example code?

**Comment by amit1911** [comment]
sorry it was a flexbox issue. fixed it and it works fine now. will close this issue.
