### ISSUE TITLE
Manual trigger of resize?

### ISSUE THREAD

**Issue by cammanderson** [digidem/react-dimensions#29]
Hi Guys, 

We are experimenting away with this HOC component at the moment. Looks like it fits the bill nicely :-) Good stuff!

One thing that we have found though. We have a 3rd party library which is loading into a DIV. When the DIV is initially drawn on page, it has a height of 0px. When the library loads in and attaches to that DIV, the HOC component containerHeight property is not updated for some reason. 

This might be a bug in our implementation, but failing that, is there a way to manually trigger a resize event here?

Thanks
Cam

**Comment by gmaclennan** [comment]
Hi @cammanderson, `react-dimensions` relies of `window` `resize` for updates by default, but you can try the (semi-experimental) `options.elementResize: true` and it will listen to the element being resized - this probably won't work in IE 9 or less. The other option for manual resizing is a prop `updateDimensions()` which is passed down to the container component and will force dimensions to be updated.

**Comment by cammanderson** [comment]
Appreciate the _very_ fast response :-) Thanks for that!

**Comment by gmaclennan** [comment]
Closing, I think this is resolved.
