### ISSUE TITLE
Handle other layout changes

### ISSUE THREAD

**Issue by langri-sha** [digidem/react-dimensions#4]
I was wondering whether it would be possible to optimally track other events that cause the parent container to recalculate it's dimensions? For instance, if a flexbox sibling suddenly becomes greedier, the parent container will resize, but the window dimensions are still the same.

**Comment by gmaclennan** [comment]
Good question. There is no resize event on anything other than window. I am thinking maybe we should calculate width and height on every render, so if you resized the flexbox you would just re-render this component. Not sure about performance implications?

**Comment by danielearwicker** [comment]
This is definitely needed. The [classic resize plugin for jQuery](http://benalman.com/code/projects/jquery-resize/examples/resize/) did this by setting up a timer, which has the advantage that it will always work, even when your content is hosted inside some other framework (in React's case, this would cover situations where `Component.render()` has not been called again, but the browser has resized content some other way).

**Comment by mindjuice** [comment]
I just submitted an implementation of "always calculate width/height on each render" in PR #17.

Still needs some work, but let me know what you think.

**Comment by mindjuice** [comment]
LOL...just noticed the other PRs addressing some of the same things. :smile:

**Comment by tnrich** [comment]
Any movement on this issue? It would be very nice if the recalculation occurred not just on window resizes..

Thanks!

**Comment by tnrich** [comment]
Sweet thanks @gmaclennan !
