### ISSUE TITLE
Fallback when requestAnimationFrame is unavailable

### ISSUE THREAD

**Issue by beheh** [digidem/react-dimensions#49]
Some browsers visiting my site do not seem to support requestAnimationFrame - e.g. an extremely outdated Chrome 23. While I do not really want to support these browsers it should be easy enough to just manually execute the wrapped function if `window.requestAnimationFrame` is undefined.

**Comment by gmaclennan** [comment]
Use a polyfill. Lots of options. One here: https://polyfill.io/v2/docs/

**Comment by beheh** [comment]
Good point, thanks!

**Comment by hustcc** [comment]
Add polyfill is not the best method to fixed `window.requestAnimationFrame` is undefined.

Because of babel 6 add `use strict` by default. add plugin `transform-remove-strict-mode` will be ok.

https://github.com/KyleAMathews/element-resize-event/issues/29
