### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by austinmao** [digidem/react-dimensions#5]
Would you please update the npm package so we can get rid of the ugly React findDOMNode warnings? :)

**Comment by neverfox** [comment]
Also, a postinstall build script would make it possible to install directly from github for moments just like these.

**Comment by jschr** [comment]
+1

**Comment by matneyx** [comment]
+1

**Comment by gmaclennan** [comment]
My apologies. npm version was published (v1.0.0) but since I published an update to v0.1.1 npm was installing that by default. Should be working now with v1.0.1

**Comment by neverfox** [comment]
:+1:
